name: dart_extensions
description: Set of method-extensions for dart that makes using framework in a much easier and clean way also adds additional functionality.
version: 2.2.3
documentation: https://github.com/droididan/dart_extentions
homepage: https://github.com/droididan/dart_extentions

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  intl: ^0.18.1
  quiver: ^3.2.1
  http: ^1.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  test: 1.17.1
